// ─── DONNÉES DES PROJETS ──────────────────────────────────────────────────────

export const FEATURED = [
  {
    id: 1, title: "Canal+U", category: "Design d'Innovation", year: "2023",
    image: "/projets/canalu/cover.jpg",
    images: [
      "/projets/canalu/cover.jpg",
      "/projets/canalu/team.jpg",
      "/projets/canalu/display.jpg",
      "/projets/canalu/media.jpg",
    ],
    tags: [
      { label: "3D", cat: "domain" },
      { label: "Unreal Engine 5", cat: "tool" },
      { label: "Blender", cat: "tool" },
      { label: "Direction artistique", cat: "domain" },
      { label: "Gestion de projet", cat: "domain" },
    ],
    accent: "#D4A574",
    desc: "Plateforme de streaming immersive, participative et interactive pour Canal+",
    role: "Lead Designer", team: "20 personnes", duration: "2 semaines",
    contexte: "Canal+ souhaitait marquer le lancement de leur offre jeunesse avec une expérience live immersive. Nous avons conçu un dispositif 3D interactif utilisable en temps réel par le public présent sur l'événement.",
    contribution: "J'ai pris en charge la direction artistique complète et coordonné une équipe de 20 personnes sur 2 semaines de production intensive. Le style visuel a été développé sous Unreal Engine 5, avec la modélisation 3D réalisée sous Blender.",
    resultats: "Livré dans les délais, le dispositif a accueilli plus de 500 visiteurs lors de l'événement. Canal+ a reconduit la collaboration suite aux retours positifs.",
    lien: "https://www.behance.net/gallery/178570041/CanalU",
  },
  {
    id: 2, title: "Disney", category: "Design Print & Web", year: "2023",
    image: "/projets/disney/cover.jpg",
    images: [
      "/projets/disney/cover.jpg",
      "/projets/disney/bingo_disney_hotel_01.jpg",
      "/projets/disney/bingo_disney_hotel_02.jpg",
      "/projets/disney/disney_activity_book.jpg",
    ],
    tags: [
      { label: "Design Print", cat: "domain" },
      { label: "Figma", cat: "tool" },
      { label: "Photoshop", cat: "tool" },
      { label: "InDesign", cat: "tool" },
      { label: "Design Web", cat: "domain" },
      { label: "Gestion de projet", cat: "domain" },
    ],
    accent: "#D4A574",
    desc: "Supports print & digitaux pour Disney Hotels : jeu de bingo, livret d'activités et assets web. Project Lead sur 8 mois avec une équipe de 12.",
    role: "Project Lead", team: "12 personnes", duration: "8 mois",
    contexte: "Disney Hotels souhaitait enrichir l'expérience client en proposant des supports créatifs autour de ses personnages emblématiques. Cela couvrait un jeu de bingo, un livret d'activités et des assets web, tous soumis à une charte graphique très stricte. Le processus de validation Disney implique des cycles longs et des exigences précises sur l'usage des personnages, ce qui rendait chaque livrable particulièrement encadré.",
    contribution: "J'ai piloté une équipe de 12 personnes en charge du design print, web et production. En plus du planning et des briefs, j'ai travaillé directement sur les créations sous Figma, Photoshop et InDesign. J'ai servi de point de contact avec les équipes Disney pour les revues de validation et les retours sur les livrables.",
    resultats: "Tous les supports ont été validés par Disney après plusieurs rounds de révision et sont aujourd'hui distribués dans les hôtels. Ce projet a ouvert la voie à de nouvelles collaborations dans le secteur de l'entertainment.",
  },
  {
    id: 3, title: "Digital Event", category: "Application mobile", year: "2023",
    image: "https://esd-digital-event.com/2026/wp-content/uploads/2026/02/CreativeTech-Photo-3.jpg",
    images: [
      "https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=1200&q=85",
      "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=1200&q=85",
      "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=1200&q=85",
      "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=1200&q=85",
      "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=1200&q=85",
    ],
    tags: [
      { label: "UI/UX", cat: "domain" },
      { label: "Motion design", cat: "domain" },
      { label: "Figma", cat: "tool" },
      { label: "After Effects", cat: "tool" },
    ],
    accent: "#D4A574",
    desc: "App de méditation immersive avec sound design custom. Coordination de 5 personnes.",
    role: "Product Designer", team: "5 personnes", duration: "4 mois",
    contexte: "[Décris ici le contexte du projet Disney : brief, enjeux, public cible, contraintes…]",
    contribution: "[Décris ici ta contribution : design des écrans, animations, coordination de l'équipe de 5…]",
    resultats: "[Décris ici les résultats : retours utilisateurs, métriques d'engagement, retour client…]",
  },
  {
    id: 4, title: "Color & Type Lab", category: "Outil interactif", year: "2024",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&q=85",
      "https://images.unsplash.com/photo-1541701494587-cb58502866ab?w=1200&q=85",
    ],
    tags: [
      { label: "UI/UX", cat: "domain" },
      { label: "Design system", cat: "domain" },
      { label: "React", cat: "tool" },
      { label: "Figma", cat: "tool" },
    ],
    accent: "#D4A574",
    desc: "Un outil interactif pour tester et analyser des combinaisons de couleurs et de typographies. Essaie la tienne !",
    role: "Designer & Développeur", team: "Solo", duration: "En continu",
    contexte: "[Décris ici le contexte de ce projet de direction artistique : commanditaire, objectif, contraintes créatives…]",
    contribution: "[Décris ici ton travail : concept, illustrations, choix typographiques, production…]",
    resultats: "[Décris ici les résultats : diffusion, retours, récompenses éventuelles…]",
  },
];

export const CAROUSEL = [
  {
    id: 11, title: "The Mountains", category: "Cinématique 3D", year: "2023",
    image: "https://img.youtube.com/vi/ej5401UoiH4/maxresdefault.jpg",
    tags: [{ label: "3D", cat: "domain" }, { label: "Unreal Engine 5", cat: "tool" }, { label: "GAEA", cat: "tool" }],
    accent: "#D4A574",
    page: "mountains",
  },
  {
    id: 12, title: "Retroverse", category: "Installation 3D", year: "2023",
    image: "https://img.youtube.com/vi/u_IxNJnyuwI/maxresdefault.jpg",
    tags: [{ label: "3D", cat: "domain" }, { label: "Motion design", cat: "domain" }, { label: "Unreal Engine 5", cat: "tool" }],
    accent: "#D4A574",
    page: "retroverse",
  },
  {
    id: 13, title: "Le Temple du Sakura", category: "Cinématique 3D · Musique", year: "2023",
    image: "https://img.youtube.com/vi/pJ_CZmqbvvg/maxresdefault.jpg",
    tags: [{ label: "3D", cat: "domain" }, { label: "Motion design", cat: "domain" }, { label: "Unreal Engine 5", cat: "tool" }],
    accent: "#D4A574",
    page: "sakura",
  },
];
